-- WorkTracker schema for Supabase (PostgreSQL)
-- Run in Supabase SQL Editor: https://supabase.com/dashboard → SQL → New query

create table if not exists public.wt_users (
  id bigint generated by default as identity primary key,
  username text not null unique,
  display_name text not null default '',
  email text not null default '',
  password_hash text not null,
  salt text not null,
  role text not null default 'user',
  discord_id text not null default '',
  last_seen_at timestamptz,
  last_seen_ip text,
  created_at timestamptz not null default now()
);

-- Idempotent column add for already-deployed schemas
alter table public.wt_users add column if not exists discord_id text not null default '';
alter table public.wt_users add column if not exists last_seen_at timestamptz;
alter table public.wt_users add column if not exists last_seen_ip text;

create table if not exists public.wt_settings (
  key text primary key,
  password_hash text not null,
  salt text not null
);

create table if not exists public.wt_projects (
  id bigint generated by default as identity primary key,
  name text not null default '',
  notes text not null default '',
  type text not null default 'project',
  status text not null default 'active',
  priority text not null default 'medium',
  owner_id bigint not null references public.wt_users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.wt_milestones (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.wt_projects(id) on delete cascade,
  title text not null default '',
  due_date text not null default '',
  status text not null default 'pending',
  weight int not null default 1,
  created_at timestamptz not null default now()
);

create table if not exists public.wt_tasks (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.wt_projects(id) on delete cascade,
  milestone_id bigint references public.wt_milestones(id) on delete set null,
  assignee_id bigint references public.wt_users(id) on delete set null,
  title text not null default '',
  due_date text not null default '',
  status text not null default 'todo',
  priority text not null default 'medium',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.wt_tasks add column if not exists assignee_id bigint references public.wt_users(id) on delete set null;

create table if not exists public.wt_updates (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.wt_projects(id) on delete cascade,
  user_id bigint references public.wt_users(id),
  content text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.wt_attachments (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.wt_projects(id) on delete cascade,
  uploaded_by bigint not null references public.wt_users(id),
  file_name text not null default 'file',
  mime_type text not null default 'application/octet-stream',
  storage_path text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.wt_activity_log (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.wt_users(id),
  project_id bigint references public.wt_projects(id) on delete set null,
  action text not null,
  entity_type text not null default 'system',
  entity_id bigint,
  details text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.wt_notifications (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.wt_users(id) on delete cascade,
  actor_user_id bigint references public.wt_users(id) on delete set null,
  type text not null default 'info',
  entity_type text,
  entity_id bigint,
  project_id bigint references public.wt_projects(id) on delete set null,
  message text not null default '',
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.wt_webhooks (
  id bigint generated by default as identity primary key,
  scope text not null,
  project_id bigint references public.wt_projects(id) on delete cascade,
  name text not null default '',
  url text not null,
  channel_url text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists wt_projects_owner_id_idx on public.wt_projects(owner_id);
create index if not exists wt_tasks_project_id_idx on public.wt_tasks(project_id);
create index if not exists wt_tasks_assignee_id_idx on public.wt_tasks(assignee_id);
create index if not exists wt_attachments_project_id_idx on public.wt_attachments(project_id);
create index if not exists wt_activity_log_project_id_idx on public.wt_activity_log(project_id);
create index if not exists wt_notifications_user_id_idx on public.wt_notifications(user_id);
create index if not exists wt_webhooks_project_id_idx on public.wt_webhooks(project_id);

insert into storage.buckets (id, name, public)
values ('project-files', 'project-files', true)
on conflict (id) do nothing;

alter table public.wt_users enable row level security;
alter table public.wt_settings enable row level security;
alter table public.wt_projects enable row level security;
alter table public.wt_tasks enable row level security;
alter table public.wt_milestones enable row level security;
alter table public.wt_updates enable row level security;
alter table public.wt_attachments enable row level security;
alter table public.wt_activity_log enable row level security;
alter table public.wt_notifications enable row level security;
alter table public.wt_webhooks enable row level security;

do $$ declare t text;
begin
  foreach t in array array[
    'wt_users','wt_settings','wt_projects','wt_tasks','wt_milestones',
    'wt_updates','wt_attachments','wt_activity_log','wt_notifications','wt_webhooks'
  ] loop
    execute format('drop policy if exists wt_anon_all on public.%I', t);
    execute format(
      'create policy wt_anon_all on public.%I for all to anon, authenticated using (true) with check (true)',
      t
    );
  end loop;
end $$;

drop policy if exists wt_storage_read on storage.objects;
drop policy if exists wt_storage_write on storage.objects;
drop policy if exists wt_storage_delete on storage.objects;
create policy wt_storage_read on storage.objects for select to anon, authenticated using (bucket_id = 'project-files');
create policy wt_storage_write on storage.objects for insert to anon, authenticated with check (bucket_id = 'project-files');
create policy wt_storage_delete on storage.objects for delete to anon, authenticated using (bucket_id = 'project-files');

-- Reload PostgREST schema cache so new tables are visible immediately
notify pgrst, 'reload schema';
